### ISSUE TITLE
Views en Partials

### ISSUE THREAD

**Issue by MarjoleinAardewijn** [ReiniervanLimpt/progressive-web-apps-1920#2]
https://github.com/ReiniervanLimpt/progressive-web-apps-1920/blob/1873ef531ccda35fd020bbfc9607350bcb3e37ce/docs/views/detail.ejs#L3

De `<body>` tag zou je ook in je `head.ejs` partial kunnen zetten. Daarnaast zou je ook de closing tag hiervan in de `footer` partial kunnen zetten. Op deze manier heb je dan alleen de content in de views staan. En kan je bijv ook als je nog client side JS code krijgt die je overal nodig hebt dat alleen in de `footer` partial zetten.

**Comment by ReiniervanLimpt** [comment]
Ook gefixed danku!
