### ISSUE TITLE
Static folder

### ISSUE THREAD

**Issue by MarjoleinAardewijn** [ReiniervanLimpt/progressive-web-apps-1920#3]
https://github.com/ReiniervanLimpt/progressive-web-apps-1920/blob/1873ef531ccda35fd020bbfc9607350bcb3e37ce/docs/scripts/build-css.js#L7

Het is mooier om je `styles.css` in een folder die bijv `src` heet zetten en dan de gecompilede versies van de bestanden in `static` zetten. Op deze manier houd je daar dan een beetje onderscheid tussen en is vooral handig als je bijv met meerdere CSS of JS files werkt, want dan kan je deze makkelijk naar 1 file compilen.

**Comment by ReiniervanLimpt** [comment]
Thanks!! dit heb ik inderdaad gedaan met behulp van het voorbeeld van Declan, ik had namelijk ook al het probleem dat ik mijn static file met rimraf heb verwijderd... nu heet de source map inderdaad src!
